unique="gnu-make"
desc="GNU Male"

[[cards]]
title="赋值表达式"
content="""
```sh
uglify = $(uglify)        # 在执行时赋值，允许递归
compressor := $(uglify)   # 在定义时赋值
prefix ?= /usr/local      # 只有在该变量为空时才赋值
hello += world            # 将值追加到变量的尾端
```
"""

[[cards]]
title="自动变量（Automatic Variables）"
content="""
`$@`指代当前目标，就是`make`命令当前构建的那个目标。
```sh
a.txt b.txt: 
    touch $@
```
等同于下面的写法：
```sh
a.txt:
    touch a.txt
b.txt:
    touch b.txt
```
"""

[[cards]]
title="函数（Functions）"
content="""
`Makefile`还可以使用[函数](http://www.gnu.org/software/make/manual/html_node/Functions.html)，格式如下。
```sh
$(function arguments)
# 或者
${function arguments}
```
## `wildcard`函数：
> `wildcard`函数用来在`Makefile`中，替换`Bash`的通配符。
```sh
srcfiles := $(wildcard src/*.txt)
```
"""