unique="apt"
desc="Advanced Packaging Tool"

[[cards]]
title="Basic Configuration"
content="""

#### 配置文件
```sh
/etc/apt/sources.list
/etc/apt/sources.list.d
```
"""

[[cards]]
title="Installing packages"
content="""
```sh
apt-get install package-name
```
"""

[[cards]]
title="Removing packages"
content="""
#### 卸载软件
```sh
apt-get remove package-name
```

#### 卸载软件并移除相关配置文件
```sh
apt-get purge package-name
```
"""

[[cards]]
title="Upgrading packages"
content="""
```sh
apt-get -u upgrade
```
"""

[[cards]]
title="Upgrading to a new release"
content="""
```sh
apt-get -u dist-upgrade
```
"""

[[cards]]
title="Removing unused package files"
content="""
```sh
apt-get clean
apt-get autoclean
```
"""